# Generated by Django 4.0.1 on 2022-04-24 22:05

import ckeditor.fields
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('content_ar', ckeditor.fields.RichTextField()),
                ('content_en', ckeditor.fields.RichTextField()),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name_en')),
                ('picture', models.ImageField(upload_to='proj-icons/')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
