# Generated by Django 4.0.1 on 2022-01-28 15:33

import ckeditor.fields
import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', ckeditor.fields.RichTextField(help_text='Name of Furniture', null=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('description_1', ckeditor.fields.RichTextField(help_text='Description of Wood Type', null=True)),
                ('description_2', ckeditor.fields.RichTextField(help_text='Description of Materials type', null=True)),
                ('description_3', ckeditor.fields.RichTextField(help_text='Description ', null=True)),
                ('size', models.CharField(blank=True, help_text='Dimensions of Item ', max_length=255, null=True)),
                ('code', models.CharField(blank=True, help_text='Code For Furniture Item', max_length=255, null=True, unique=True)),
                ('picture_1', models.ImageField(help_text='first Image of item', upload_to='furniture')),
                ('picture_2', models.ImageField(help_text='second Image of item', null=True, upload_to='furniture')),
                ('picture_3', models.ImageField(help_text='third Image of item', null=True, upload_to='furniture')),
                ('picture_4', models.ImageField(help_text='fourth Image of item', null=True, upload_to='furniture')),
                ('color', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None)),
                ('catgeory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furniture.category')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
