# Generated by Django 4.0.1 on 2022-01-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0002_furniture'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='furniture',
            name='is_for_offer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='furniture',
            name='offer_value',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
