# Generated by Django 4.0.1 on 2022-01-28 17:12

import ckeditor.fields
import colorfield.fields
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0003_furniture_date_added_furniture_is_for_offer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WoodInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('wood_name', models.CharField(blank=True, help_text='Name of Wood', max_length=255, null=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='wood_name')),
                ('description_1', ckeditor.fields.RichTextField(null=True)),
                ('description_2', ckeditor.fields.RichTextField(null=True)),
                ('description_3', ckeditor.fields.RichTextField(null=True)),
                ('description_4', ckeditor.fields.RichTextField(null=True)),
                ('image_1', models.ImageField(upload_to='woods/')),
                ('image_2', models.ImageField(null=True, upload_to='woods/')),
                ('image_3', models.ImageField(null=True, upload_to='woods/')),
                ('color', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
