# Generated by Django 4.0.1 on 2022-02-11 18:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0005_rename_name_category_name_ar_category_name_en'),
    ]

    operations = [
        migrations.RenameField(
            model_name='furniture',
            old_name='description_1',
            new_name='description_1_ar',
        ),
        migrations.RenameField(
            model_name='furniture',
            old_name='description_2',
            new_name='description_2_ar',
        ),
        migrations.RenameField(
            model_name='furniture',
            old_name='description_3',
            new_name='description_3_ar',
        ),
        migrations.RenameField(
            model_name='furniture',
            old_name='name',
            new_name='name_ar',
        ),
        migrations.AddField(
            model_name='furniture',
            name='description_1_en',
            field=ckeditor.fields.RichTextField(help_text='Description of Wood Type', null=True),
        ),
        migrations.AddField(
            model_name='furniture',
            name='description_2_en',
            field=ckeditor.fields.RichTextField(help_text='Description of Materials type', null=True),
        ),
        migrations.AddField(
            model_name='furniture',
            name='description_3_en',
            field=ckeditor.fields.RichTextField(help_text='Description ', null=True),
        ),
        migrations.AddField(
            model_name='furniture',
            name='name_en',
            field=ckeditor.fields.RichTextField(help_text='Name of Furniture', null=True),
        ),
    ]
