# Generated by Django 4.0.1 on 2022-02-11 19:08

import ckeditor.fields
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0007_alter_category_slug_alter_furniture_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='woodinformation',
            old_name='description_1',
            new_name='description_1_ar',
        ),
        migrations.RenameField(
            model_name='woodinformation',
            old_name='description_2',
            new_name='description_1_en',
        ),
        migrations.RenameField(
            model_name='woodinformation',
            old_name='description_3',
            new_name='description_2_ar',
        ),
        migrations.RenameField(
            model_name='woodinformation',
            old_name='description_4',
            new_name='description_2_en',
        ),
        migrations.RenameField(
            model_name='woodinformation',
            old_name='wood_name',
            new_name='wood_name_ar',
        ),
        migrations.AddField(
            model_name='woodinformation',
            name='description_3_ar',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='woodinformation',
            name='description_3_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='woodinformation',
            name='description_4_ar',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='woodinformation',
            name='description_4_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='woodinformation',
            name='wood_name_en',
            field=models.CharField(blank=True, help_text='Name of Wood', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='woodinformation',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='wood_name_en'),
        ),
    ]
