# Generated by Django 4.0.1 on 2022-02-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0008_rename_description_1_woodinformation_description_1_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='woodinformation',
            name='is_ready',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
