# Generated by Django 4.0.1 on 2022-02-18 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0011_alter_woodinformation_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='woodinformation',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='furniture.category'),
        ),
    ]
