# Generated by Django 4.0.1 on 2022-02-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0012_woodinformation_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='woodinformation',
            name='color',
        ),
    ]
