# Generated by Django 4.0.1 on 2022-05-04 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('furniture', '0015_alter_woodinformation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='catgeory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='projects.projecttypes'),
        ),
    ]
