# Generated by Django 4.0.1 on 2022-05-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0016_alter_furniture_catgeory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='picture_1',
            field=models.ImageField(blank=True, help_text='first Image of item', null=True, upload_to='furniture'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='picture_2',
            field=models.ImageField(blank=True, help_text='second Image of item', null=True, upload_to='furniture'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='picture_3',
            field=models.ImageField(blank=True, help_text='third Image of item', null=True, upload_to='furniture'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='picture_4',
            field=models.ImageField(blank=True, help_text='fourth Image of item', null=True, upload_to='furniture'),
        ),
    ]
