# Generated by Django 4.0.1 on 2022-02-11 19:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_homepage_show_section_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='address_ar',
            field=ckeditor.fields.RichTextField(help_text='Address [Arabic]', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='address_en',
            field=ckeditor.fields.RichTextField(help_text='Address [English]', null=True),
        ),
    ]
