# Generated by Django 4.0.1 on 2022-04-22 11:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_blogpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('content_ar', ckeditor.fields.RichTextField()),
                ('content_en', ckeditor.fields.RichTextField()),
                ('background', models.ImageField(null=True, upload_to='backgrounds/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
