# Generated by Django 4.0.1 on 2022-04-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='is_show',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
