# Generated by Django 4.0.1 on 2022-04-24 00:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_faq_is_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('head_en', models.CharField(blank=True, max_length=255, null=True)),
                ('description_en', ckeditor.fields.RichTextField()),
                ('description_ar', ckeditor.fields.RichTextField()),
                ('background', models.ImageField(null=True, upload_to='background/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
