# Generated by Django 4.0.1 on 2022-05-03 06:40

import ckeditor.fields
import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_faq_answer_remove_faq_question_faq_answer_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='twitter_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='youtube_link',
        ),
        migrations.AddField(
            model_name='homepage',
            name='first_reason_ar',
            field=models.CharField(blank=True, help_text='First Reason [Arabic]', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='first_reason_description_ar',
            field=ckeditor.fields.RichTextField(help_text='First reason Description[Arabic]', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='first_reason_description_en',
            field=ckeditor.fields.RichTextField(help_text='First reason Description[English]', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='first_reason_en',
            field=models.CharField(blank=True, help_text='First Reason [English]', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='second_reason_ar',
            field=models.CharField(blank=True, help_text='Second Reason [Arabic]', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='second_reason_description_ar',
            field=ckeditor.fields.RichTextField(help_text='Second reason Description[Arabic]', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='second_reason_description_en',
            field=ckeditor.fields.RichTextField(help_text='Second reason Description[English]', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='second_reason_en',
            field=models.CharField(blank=True, help_text='Second Reason [English]', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='third_reason_ar',
            field=models.CharField(blank=True, help_text='Third Reason [Arabic]', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='third_reason_description_ar',
            field=ckeditor.fields.RichTextField(help_text='Third reason Description[Arabic]', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='third_reason_description_en',
            field=ckeditor.fields.RichTextField(help_text='Third reason Description[English]', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='third_reason_en',
            field=models.CharField(blank=True, help_text='Third Reason [English]', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_us_description_ar',
            field=ckeditor.fields.RichTextField(help_text='Why us Description [Arabic]', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_us_description_en',
            field=ckeditor.fields.RichTextField(help_text='Why us Description [English]', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_us_title_ar',
            field=models.CharField(blank=True, help_text='Why Us Tiltle [Arabic]', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_us_title_en',
            field=models.CharField(blank=True, help_text='Why Us Tiltle [English]', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='btn_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='Button Color in Intro', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='btn_text_ar',
            field=models.CharField(blank=True, help_text='button in Intro Text [Arabic]', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='btn_text_en',
            field=models.CharField(blank=True, help_text='Button Text in Intro [Arabic]', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='category_description_ar',
            field=ckeditor.fields.RichTextField(help_text='Category Description for blogs [Arabic]', null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='category_description_en',
            field=ckeditor.fields.RichTextField(help_text='Category Description for blogs [English]', null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='category_title_ar',
            field=models.CharField(blank=True, help_text='Category Tiltles for blogs [Arabic]', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='category_title_en',
            field=models.CharField(blank=True, help_text='Category Tiltles for blogs [English]', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='header_ar',
            field=ckeditor.fields.RichTextField(help_text='Intro Header [Arabic]', null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='header_en',
            field=ckeditor.fields.RichTextField(help_text='Intro Header [English]', null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='subheader_ar',
            field=models.CharField(blank=True, help_text='Content in Intro [Arabic]', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='subheader_en',
            field=models.CharField(blank=True, help_text='Content in Intro [English]', max_length=255, null=True),
        ),
    ]
