# Generated by Django 4.0.1 on 2022-05-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
