# Generated by Django 4.0.1 on 2022-05-03 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_staff_facebook_url_staff_instagram_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='show_section_background',
        ),
    ]
