# Generated by Django 4.0.1 on 2022-05-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_homepage_show_section_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
